input:
  # CockroachDB Input
  label: ""
  cockroachdb_changefeed:
    dsn: postgresql://<user>:<password>@<clustername>.cockroachlabs.cloud:<port>/<clustername>.<database>?sslmode=verify-full
    tls:
      skip_cert_verify: true
      #enable_renegotiation: false
      #root_cas: ""
      #root_cas_file: ""
      client_certs: []
    tables: [cdc_table] # No default (required)
    cursor_cache: "" # No default (optional)
    auto_replay_nacks: true

pipeline:
  processors: []

output:
  # Snowflake Output
  label: ""
  snowflake_put:
    account: <ACCOUNT>
    user: <USER>
    private_key_file: rsa_key.pem
    role: <ROLE>
    database: <DATABASE>
    warehouse: <WAREHOUSE>
    schema: <SCHEMA>
<<<<<<< HEAD
    stage: "@%IMPLICIT_TABLE_STAGE"
=======
    stage: "@%IMPLICIT_TABLE_STAGE_NAME"
>>>>>>> cd5b3ff (updated)
    path: "path"
    upload_parallel_threads: 4
    compression: NONE
    batching:
      count: 10
      period: 3s
      processors:
        - archive:
            #format: concatenate
            format: json_array
    max_in_flight: 1